create table schemas (
	id int PRIMARY KEY not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
	name  VARCHAR(100) not null,
	root varchar(100) not null,
	xsd clob not null
); 

create table statements (
	id int PRIMARY KEY not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
	name  VARCHAR(100) not null,
	epl   VARCHAR(10000) not null,
	state VARCHAR(10) not null,
	ttl   INTEGER not null CONSTRAINT positive_ttl CHECK (ttl >= 0)
);

CREATE KEYSPACE thesis WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
USE thesis;
create table statement_results(
  time_id timeuuid,
  statement_id int,
  event text,
primary key (statement_id, time_id))
with clustering order by (time_id desc) and gc_grace_seconds = 0;



insert into statements(epl,name,state,ttl) values ('select * from TweetEvent where message like ''%happy%''','11happy','STARTED',86400);
