source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'her', :git => 'https://github.com/kravciak/her.git'
gem 'sqlite3' # Use sqlite3 as the database for Active Record

# Bootstrap
gem 'bootstrap-sass', '~> 3.2.0'
gem 'font-awesome-sass', '~> 4.2.0'
gem 'autoprefixer-rails'
# BreadCrumbs
gem "gretel"
# Pagination + bootstrap
gem 'will_paginate', '~> 3.0.5'
gem 'bootstrap-will_paginate'

# Display formatted XML, JSON
gem 'coderay'
gem 'nokogiri'

# Assets
gem 'sass-rails', '>= 4.0.0'  # Use SCSS for stylesheets
gem 'uglifier', '>= 1.3.0'  # Use Uglifier as compressor for JavaScript assets
gem 'coffee-rails', '~> 4.0.0'  # Use CoffeeScript for .js.coffee assets and views

gem 'turbolinks'  # Turbolinks makes following links in your web application faster.
gem 'jquery-turbolinks'

gem 'jquery-rails'  # Use jquery as the JavaScript library

gem 'jbuilder', '~> 1.2'  # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development do
  gem 'better_errors'
  gem 'awesome_print'
  gem 'quiet_assets'
  gem 'binding_of_caller'
end

gem 'chronic_duration'
gem 'uuidtools'

# Security
#gem 'cancan', '~> 1.6.10'
#gem 'devise', '~> 3.3.0'

#gem 'paperclip', '~> 4.2.0' # Image uploads

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
